# Generated by Django 5.1.3 on 2024-12-13 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_birth_alter_customuser_reletion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='reletion',
            new_name='relation',
        ),
    ]
