# Generated by Django 5.1.3 on 2025-01-03 11:58

import django.db.models.deletion
import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر برند'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر کالا'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر کالا'),
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=100, verbose_name='عنوان گروه کالا')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر کروه کالا')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات گروه کالا')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال / غیر فعال')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('group_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='products.productgroup', verbose_name='والد گروه کالا')),
            ],
            options={
                'verbose_name': 'گروه ها',
                'verbose_name_plural': 'گروه های کالا',
            },
        ),
        migrations.AlterField(
            model_name='feature',
            name='product_group',
            field=models.ManyToManyField(related_name='features_of_groups', to='products.productgroup', verbose_name='گروه غذاها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.ManyToManyField(related_name='products_of_groups', to='products.productgroup', verbose_name='گروه کالاها'),
        ),
        migrations.DeleteModel(
            name='FoodGroup',
        ),
    ]
